title: Yubo Du
position: Ph.D. Student
affiliation: University of Pittsburgh
email: yubo.du (at) pitt.edu
keywords: minimal academic
github_link: https://github.com/duyubo
google_scholar: https://scholar.google.com/citations?user=q8kKxSYAAAAJ&hl=en
linkedin: https://www.linkedin.com/in/yubo-du-370b4118a
avatar: ./assets/img/yubodu.jpg
favicon: ./assets/img/yubodu.jpg
favicon_dark: ./assets/img/yubodu.jpg
description: Yubo Du's homepage
canonical: duyubo.github.io/yubodu.github.io
remote_theme: yaoyao-liu/minimal-light
