title: Yongbin Feng
position: Postdoctoral Research Associate
affiliation: Fermi National Accelerator Laboratory
email: yourname (at) fnal.gov
keywords: minimal academic
github_link: https://github.com/yongbinfeng
linkedin: https://www.linkedin.com/in/yongbin-feng-433962158/
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://yongbinfeng.github.io
remote_theme: yaoyao-liu/minimal-light
