title: Yubo Du
position: Ph.D. Student
affiliation: University of Pittsburgh
email: yubo.du (at) pitt.edu
keywords: minimal academic
github_link: https://github.com/duyubo
avatar: ./assets/img/yubo_du.jpg
favicon: ./assets/img/w_decay.jpg
favicon_dark: ./assets/img/w_decay.jpg
description: Yubo Du's homepage
canonical: https://yubodu.github.io
remote_theme: yaoyao-liu/minimal-light
