title: Yongbin Feng
position: Postdoctoral Research Associate
affiliation: Fermilab
email: yfeng (at) fnal.gov
keywords: minimal academic
github_link: https://github.com/yongbinfeng
linkedin: https://www.linkedin.com/in/yongbin-feng-433962158/
avatar: ./assets/img/yongbin_feng.png
favicon: ./assets/img/w_decay.png
favicon_dark: ./assets/img/w_decay.png
description: Yongbin Feng's homepage
canonical: https://yongbinfeng.github.io
remote_theme: yaoyao-liu/minimal-light
